In [1]:
import pandas as pd

In [2]:
# read csv(comma seperated values)

df = pd.read_csv('student_data.csv')
df.head()
# df.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [4]:
particular_colum = df['FullName']

In [5]:
# column

col = df.columns
print(col)

col_list = list(col)
print(col_list)

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='str')
['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']

In [6]:
# index
print(df.index)

RangeIndex(start=0, stop=20, step=1)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     str
 1   FullName              20 non-null     str
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     str
 6   EnrollmentDate        20 non-null     str
 7   Instructor            20 non-null     str
 8   Location              20 non-null     str
dtypes: float64(3), str(6)
memory usage: 2.6 KB

In [8]:
# check some rows randomly

df.sample(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [9]:
# describe() -> shows a statistical summary of the numerical columns

df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

#### Converting existing data to DataFrame

In [10]:
# list

my_list = [['alice', 25], ['bob', 30], ['charlie', 28]]
my_list_df = pd.DataFrame(my_list, columns=['name', 'age'], )
print(my_list_df)

# tuple
# same as list

      name  age
0    alice   25
1      bob   30
2  charlie   28

In [11]:
# dict
my_dict = {
    'Name' : ['alice', 'bob', 'charlie'],
    'Age' : [25, 30, 28]
}

my_dict_df = pd.DataFrame(my_dict)
print(my_dict_df)

      Name  Age
0    alice   25
1      bob   30
2  charlie   28

#### Accessing data

Syntax: 
```python
DataFrame.loc[row_labels, column_labels]
```

In [12]:
# access a particular row

print(df.loc[0])

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [13]:
# access multiple rows
# syntax : loc[[rows indexes]]

df.loc[[3, 7, 0]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka

In [14]:
# multiple rows within a range

df.loc[11:15] # show the rows of indexes between 11 to 15

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram

In [15]:
# access a particular column

df.loc[:, 'Algorithm Marks']

0     85.0
1     92.0
2     88.0
3     78.0
4      NaN
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10     NaN
11    85.0
12    75.0
13     NaN
14    86.0
15    94.0
16    90.0
17    88.0
18     NaN
19    86.0
Name: Algorithm Marks, dtype: float64

In [16]:
# access multiple columns

df.loc[:, ['FullName', 'Algorithm Marks', 'CompletionStatus']]

            FullName  Algorithm Marks CompletionStatus
0        Alif Rahman             85.0        Completed
1      Fatima Akhter             92.0      In Progress
2      Imran Hossain             88.0        Completed
3   Jannatul Ferdous             78.0        Completed
4        Kamal Uddin              NaN      In Progress
5        Laila Begum             75.0        Completed
6     Mahmudul Hasan             80.0      In Progress
7        Nadia Islam             81.0        Completed
8         Omar Faruq             72.0        Completed
9       Priya Sharma             89.0        Completed
10      Rahim Sheikh              NaN      In Progress
11   Sadia Chowdhury             85.0        Completed
12      Tanvir Ahmed             75.0        Completed
13        Urmi Akter              NaN      Not Started
14      Wahiduzzaman             86.0        Completed
15      Ziaur Rahman             94.0      In Progress
16       Afsana Mimi             90.0        Completed
17       Babul Ahmed             88.0        Completed
18      Faria Rahman              NaN      Not Started
19        Nasir Khan             86.0        Completed

In [17]:
# select a specific portion of the table
# i want the values of rows 5 to 10, and i want StudentID, FullName, EnrollmentDate these columns values

df.loc[5:10, ['StudentID', 'FullName', 'EnrollmentDate']]

   StudentID        FullName EnrollmentDate
5     PH1006     Laila Begum     2024-03-08
6     PH1007  Mahmudul Hasan     2024-04-01
7     PH1008     Nadia Islam     2024-04-22
8     PH1009      Omar Faruq     2024-05-16
9     PH1010    Priya Sharma     2024-05-20
10    PH1011    Rahim Sheikh     2024-06-11

#### Changing index and columns and iloc

In [18]:
indexes = [x for x in range(1, 21)]
df2 = df.set_index('StudentID')
df2.head()

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [19]:
# in df2 the indexes are now StudentID
# now, if you want to slice or see values of a particular range, you've use iloc(). loc() would throw 
# an error here. 

# will throw an error
# df2.loc[3:7] 

df2.iloc[3:7]
# iloc is exclusive whereas loc is inclusive. the rest is pretty same

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka

In [20]:
# rename a column
print(df.head(1))
df.rename(columns={'FullName' : 'Full Name'})
print(df.head(1))

  StudentID     FullName  Data Structure Marks  Algorithm Marks  Python Marks  \
0    PH1001  Alif Rahman                  85.0             85.0          88.0

  CompletionStatus EnrollmentDate Instructor Location
0        Completed     2024-01-15  Mr. Karim    Dhaka
  StudentID     FullName  Data Structure Marks  Algorithm Marks  Python Marks  \
0    PH1001  Alif Rahman                  85.0             85.0          88.0

  CompletionStatus EnrollmentDate Instructor Location
0        Completed     2024-01-15  Mr. Karim    Dhaka

In [21]:
# no change? why? because .rename() .set_index() return a new DataFrame where changes are made. 

# solution is to set inplace=True

print(df.head(1))
df.rename(columns={'FullName' : 'Full Name', 'CompletionStatus': 'Completion Status', 'EnrollmentDate' : 'Enrollment Date'}, inplace=True)
print(df.head(1))

  StudentID     FullName  Data Structure Marks  Algorithm Marks  Python Marks  \
0    PH1001  Alif Rahman                  85.0             85.0          88.0

  CompletionStatus EnrollmentDate Instructor Location
0        Completed     2024-01-15  Mr. Karim    Dhaka
  StudentID    Full Name  Data Structure Marks  Algorithm Marks  Python Marks  \
0    PH1001  Alif Rahman                  85.0             85.0          88.0

  Completion Status Enrollment Date Instructor Location
0         Completed      2024-01-15  Mr. Karim    Dhaka

#### Drop Values

In [24]:
# delete a particular row
df2 = df.copy()
particular_row_index = 5
df2.drop(particular_row_index, inplace=True)
df2

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [25]:
# delte a particular column
df2.drop('Instructor', axis=1, inplace=True)
df2

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [26]:
# change a particular property value

print(df2.loc[4])
df2.loc[4, 'Algorithm Marks'] = 87 # set the algorithm marks to 87 of index 4
print(df2.loc[4])

StudentID                    PH1005
Full Name               Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
Completion Status       In Progress
Enrollment Date          2024-03-05
Location                 Chattogram
Name: 4, dtype: object
StudentID                    PH1005
Full Name               Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                87.0
Python Marks                   95.0
Completion Status       In Progress
Enrollment Date          2024-03-05
Location                 Chattogram
Name: 4, dtype: object

In [27]:
# change multiple values of a 

df2.loc[4, ['Algorithm Marks', 'Completion Status']] = [89, 'Completed']
print(df2.loc[4])

StudentID                    PH1005
Full Name               Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                89.0
Python Marks                   95.0
Completion Status         Completed
Enrollment Date          2024-03-05
Location                 Chattogram
Name: 4, dtype: object

In [28]:
# modify values of a particular range

print(df.head())
df.loc[:4, 'Python Marks'] += 2
df.head()

  StudentID         Full Name  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                  85.0             85.0
1    PH1002     Fatima Akhter                  92.0             92.0
2    PH1003     Imran Hossain                  88.0             88.0
3    PH1004  Jannatul Ferdous                  78.0             78.0
4    PH1005       Kamal Uddin                   NaN              NaN

   Python Marks Completion Status Enrollment Date Instructor    Location
0          88.0         Completed      2024-01-15  Mr. Karim       Dhaka
1           NaN       In Progress      2024-01-20  Ms. Salma  Chattogram
2          85.0         Completed      2024-02-10  Mr. Karim       Dhaka
3          82.0         Completed      2024-02-12  Ms. Salma      Sylhet
4          95.0       In Progress      2024-03-05  Mr. Karim  Chattogram

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,90.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,97.0,In Progress,2024-03-05,Mr. Karim,Chattogram

#### Sorting in DataFrame

In [32]:
# sort a particular column

df2.sort_values('Python Marks', inplace=True, ascending=False)
df2.head()

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Location
4,PH1005,Kamal Uddin,NaN,89.0,95.0,Completed,2024-03-05,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet

#### Filtering data based on condition

In [ ]:
# find the students whoes completion status is Not Started

not_started = df.loc[df['Completion Status'] == 'Not Started']
not_started

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Instructor,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

In [38]:
# find the students who has marks above 90 in DS and completion status is completed 

completed_ds90 = df.loc[(df['Completion Status'] =='Completed') & (df['Python Marks'] >= 90)]
completed_ds90

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,Completion Status,Enrollment Date,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,90.0,Completed,2024-01-15,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka